# SPDX-License-Identifier: AGPL-3.0-only
# @generated by tools/generate_sdk_models.py; do not edit.
from __future__ import annotations

from typing import Literal, Never, NotRequired, TypeAlias, TypedDict

CONTRACT_SHA256 = "3020230ce681b9140bf160f5ce814a1c66255546aa8fd4ac79688636bbd7b0d2"

JsonValue: TypeAlias = (
    None | bool | int | str | list["JsonValue"] | dict[str, "JsonValue"]
)

class NativeOperationResultV2(TypedDict):
    """Transport-independent operation result represented by its stable response kind and family-specific value."""
    kind: str
    value: JsonValue

class NativeReadStreamRecordV2Data(TypedDict):
    type: Literal["data"]
    provisional: Literal[True]
    sequence: int
    data_base64: str

class NativeReadStreamRecordV2Completion(TypedDict):
    type: Literal["completion"]
    status: Literal["complete"]
    request_id: str
    chunks: int
    response_bytes: int
    digest_hex: str

class NativeRequestV2(TypedDict):
    """One transport-independent Hyphae Native v2 operation and execution context."""
    request_id: str
    logical_time_micros: int
    deadline_micros: NotRequired[int | None]
    durability: DurabilityV2
    limits: ProductLimitsV2
    operation: OperationV2

class NativeResponseV2(TypedDict):
    """Definitive response after transport completion validation."""
    request_id: str
    kind: str
    value: JsonValue

class NativeV1CompatibilityPolicyV2(TypedDict):
    """Explicit policy for any v1 route exposed by a Native product service."""
    exact_mappings_only: Literal[True]
    unmappable_fails_explicitly: Literal[True]
    opens_format_2_state: Literal[False]

class OperationV2Admin(TypedDict):
    kind: Literal["admin"]
    action: str
    arguments: dict[str, JsonValue]

class OperationV2Backup(TypedDict):
    kind: Literal["backup"]
    action: str
    arguments: dict[str, JsonValue]

class OperationV2Capabilities(TypedDict):
    kind: Literal["capabilities"]

class OperationV2Catalog(TypedDict):
    kind: Literal["catalog"]
    action: str
    arguments: dict[str, JsonValue]

class OperationV2Doctor(TypedDict):
    kind: Literal["doctor"]
    arguments: dict[str, JsonValue]

class OperationV2ProofVerify(TypedDict):
    kind: Literal["proof_verify"]
    arguments: dict[str, JsonValue]

class OperationV2Search(TypedDict):
    kind: Literal["search"]
    action: str
    arguments: dict[str, JsonValue]

class OperationV2SearchCollection(TypedDict):
    kind: Literal["search_collection"]
    arguments: dict[str, JsonValue]

class OperationV2SearchIngest(TypedDict):
    kind: Literal["search_ingest"]
    arguments: dict[str, JsonValue]

class OperationV2Sql(TypedDict):
    kind: Literal["sql"]
    action: str
    arguments: dict[str, JsonValue]

class OperationV2Structure(TypedDict):
    kind: Literal["structure"]
    action: str
    arguments: dict[str, JsonValue]

class OperationV2Telemetry(TypedDict):
    kind: Literal["telemetry"]

class OperationV2TransactionStatus(TypedDict):
    kind: Literal["transaction_status"]
    arguments: dict[str, JsonValue]

class ProductErrorDetailsV2(TypedDict):
    sql_subcode: str | None
    unknown: list[ProductErrorUnknownDetailV2]

class ProductErrorLimitV2(TypedDict):
    kind: str
    configured: int
    observed: int

class ProductErrorSourceSpanV2(TypedDict):
    start: int
    end: int

class ProductErrorUnknownDetailV2(TypedDict):
    tag: int
    value_hex: str

class ProductErrorV2(TypedDict):
    """JSON representation with exact field parity to the Native ProductError contract."""
    code: str
    category: Literal["invalid-request", "not-found", "conflict", "limit", "deadline", "cancelled", "authorization", "corruption", "unavailable", "io", "internal"]
    retry: Literal["never", "same-request", "new-snapshot", "after-backoff", "after-recovery", "unknown-commit"]
    message: str
    request_id: str | None
    trace_id: str | None
    object_id: str | None
    transaction_state: Literal["none", "active", "rolled-back", "committed", "outcome-unknown"]
    transaction_id: str | None
    limit: ProductErrorLimitV2 | None
    source_span: ProductErrorSourceSpanV2 | None
    details: ProductErrorDetailsV2

class ProductLimitsV2(TypedDict):
    """Central count, byte, work, and memory envelope."""
    max_count: int
    max_request_bytes: int
    max_response_bytes: int
    max_work_units: int
    max_memory_bytes: int

DurabilityV2: TypeAlias = Literal["strict", "group", "memory"]
NativeReadStreamRecordV2: TypeAlias = NativeReadStreamRecordV2Data | NativeReadStreamRecordV2Completion
OperationV2: TypeAlias = OperationV2Capabilities | OperationV2Catalog | OperationV2Sql | OperationV2Structure | OperationV2Search | OperationV2SearchCollection | OperationV2SearchIngest | OperationV2Admin | OperationV2Telemetry | OperationV2Doctor | OperationV2Backup | OperationV2ProofVerify | OperationV2TransactionStatus

__all__ = [
    "CONTRACT_SHA256",
    "DurabilityV2",
    "JsonValue",
    "NativeOperationResultV2",
    "NativeReadStreamRecordV2",
    "NativeReadStreamRecordV2Completion",
    "NativeReadStreamRecordV2Data",
    "NativeRequestV2",
    "NativeResponseV2",
    "NativeV1CompatibilityPolicyV2",
    "OperationV2",
    "OperationV2Admin",
    "OperationV2Backup",
    "OperationV2Capabilities",
    "OperationV2Catalog",
    "OperationV2Doctor",
    "OperationV2ProofVerify",
    "OperationV2Search",
    "OperationV2SearchCollection",
    "OperationV2SearchIngest",
    "OperationV2Sql",
    "OperationV2Structure",
    "OperationV2Telemetry",
    "OperationV2TransactionStatus",
    "ProductErrorDetailsV2",
    "ProductErrorLimitV2",
    "ProductErrorSourceSpanV2",
    "ProductErrorUnknownDetailV2",
    "ProductErrorV2",
    "ProductLimitsV2",
]
