// SPDX-License-Identifier: Apache-2.0
// @generated by tools/generate_sdk_models.py; do not edit.
export const CONTRACT_SHA256 = "3020230ce681b9140bf160f5ce814a1c66255546aa8fd4ac79688636bbd7b0d2" as const;

export type JsonInteger = number | bigint;

export type JsonValue =
  | null
  | boolean
  | JsonInteger
  | string
  | Array<JsonValue>
  | { [key: string]: JsonValue };

/** Mutation acknowledgement policy. */
export type DurabilityV2 = "strict" | "group" | "memory";

/** Transport-independent operation result represented by its stable response kind and family-specific value. */
export interface NativeOperationResultV2 {
  kind: string;
  value: JsonValue;
}

/** One NDJSON record. Data records are provisional until the mandatory completion record arrives. */
export type NativeReadStreamRecordV2 = {
  type: "data";
  provisional: true;
  sequence: JsonInteger;
  data_base64: string;
} | {
  type: "completion";
  status: "complete";
  request_id: string;
  chunks: JsonInteger;
  response_bytes: JsonInteger;
  digest_hex: string;
};

/** One transport-independent Hyphae Native v2 operation and execution context. */
export interface NativeRequestV2 {
  /** Nonzero unsigned 128-bit request identity as canonical decimal text. */
  request_id: string;
  /** Logical time used by snapshots and TTL behavior. */
  logical_time_micros: JsonInteger;
  /** Optional positive absolute Unix-time deadline in microseconds. */
  deadline_micros?: JsonInteger | null;
  durability: DurabilityV2;
  limits: ProductLimitsV2;
  operation: OperationV2;
}

/** Definitive response after transport completion validation. */
export interface NativeResponseV2 {
  request_id: string;
  kind: string;
  value: JsonValue;
}

/** Explicit policy for any v1 route exposed by a Native product service. */
export interface NativeV1CompatibilityPolicyV2 {
  exact_mappings_only: true;
  unmappable_fails_explicitly: true;
  opens_format_2_state: false;
}

/** Closed high-level operation family. Arguments are family-specific typed JSON models. */
export type OperationV2 = OperationV2Capabilities | OperationV2Catalog | OperationV2Sql | OperationV2Structure | OperationV2Search | OperationV2SearchCollection | OperationV2SearchIngest | OperationV2Admin | OperationV2Telemetry | OperationV2Doctor | OperationV2Backup | OperationV2ProofVerify | OperationV2TransactionStatus;

export interface OperationV2Admin {
  kind: "admin";
  action: string;
  arguments: {
  };
}

export interface OperationV2Backup {
  kind: "backup";
  action: string;
  arguments: {
  };
}

export interface OperationV2Capabilities {
  kind: "capabilities";
}

export interface OperationV2Catalog {
  kind: "catalog";
  action: string;
  arguments: {
  };
}

export interface OperationV2Doctor {
  kind: "doctor";
  arguments: {
  };
}

export interface OperationV2ProofVerify {
  kind: "proof_verify";
  arguments: {
  };
}

export interface OperationV2Search {
  kind: "search";
  action: string;
  arguments: {
  };
}

export interface OperationV2SearchCollection {
  kind: "search_collection";
  arguments: {
  };
}

export interface OperationV2SearchIngest {
  kind: "search_ingest";
  arguments: {
  };
}

export interface OperationV2Sql {
  kind: "sql";
  action: string;
  arguments: {
  };
}

export interface OperationV2Structure {
  kind: "structure";
  action: string;
  arguments: {
  };
}

export interface OperationV2Telemetry {
  kind: "telemetry";
}

export interface OperationV2TransactionStatus {
  kind: "transaction_status";
  arguments: {
  };
}

export interface ProductErrorDetailsV2 {
  sql_subcode: string | null;
  unknown: Array<ProductErrorUnknownDetailV2>;
}

export interface ProductErrorLimitV2 {
  kind: string;
  configured: JsonInteger;
  observed: JsonInteger;
}

export interface ProductErrorSourceSpanV2 {
  start: JsonInteger;
  end: JsonInteger;
}

export interface ProductErrorUnknownDetailV2 {
  tag: JsonInteger;
  value_hex: string;
}

/** JSON representation with exact field parity to the Native ProductError contract. */
export interface ProductErrorV2 {
  code: string;
  category: "invalid-request" | "not-found" | "conflict" | "limit" | "deadline" | "cancelled" | "authorization" | "corruption" | "unavailable" | "io" | "internal";
  retry: "never" | "same-request" | "new-snapshot" | "after-backoff" | "after-recovery" | "unknown-commit";
  message: string;
  request_id: string | null;
  trace_id: string | null;
  object_id: string | null;
  transaction_state: "none" | "active" | "rolled-back" | "committed" | "outcome-unknown";
  transaction_id: string | null;
  limit: ProductErrorLimitV2 | null;
  source_span: ProductErrorSourceSpanV2 | null;
  details: ProductErrorDetailsV2;
}

/** Central count, byte, work, and memory envelope. */
export interface ProductLimitsV2 {
  max_count: JsonInteger;
  max_request_bytes: JsonInteger;
  max_response_bytes: JsonInteger;
  max_work_units: JsonInteger;
  max_memory_bytes: JsonInteger;
}
