// SPDX-License-Identifier: Apache-2.0
// @generated by tools/generate_sdk_models.py; do not edit.
export const CONTRACT_SHA256 = "fb7195bcd2d16117b0b5fd86f032db292870548c8095532d984ae583448e0656" as const;

export type JsonInteger = number | bigint;

export type JsonValue =
  | null
  | boolean
  | JsonInteger
  | string
  | Array<JsonValue>
  | { [key: string]: JsonValue };

/** Optional grouped aggregation plan. */
export interface AggregationPlanV1 {
  /** Ordered group-key paths. */
  group_by: Array<Array<string>>;
  /** Named metrics. */
  metrics: Array<NamedMetricV1>;
}

/** Complete aggregation response. */
export interface AggregationResultV1 {
  /** Whether explicit group fields were requested. */
  grouped: boolean;
  /** Deterministically ordered groups. */
  groups: Array<GroupResultV1>;
}

/** Public server policy limits. */
export interface ApiLimitsV1 {
  /** Maximum distinct aggregation groups. */
  aggregation_groups: JsonInteger;
  /** Maximum records or keys in one atomic batch. */
  batch_items: JsonInteger;
  /** Maximum admitted concurrent data operations. */
  concurrent_operations: JsonInteger;
  /** Maximum canonical structured document payload bytes. */
  document_bytes: JsonInteger;
  /** Maximum recursive filter depth. */
  filter_depth: JsonInteger;
  /** Maximum recursive filter nodes. */
  filter_nodes: JsonInteger;
  /** Maximum aggregation group fields. */
  group_fields: JsonInteger;
  /** Maximum JSON nesting depth. */
  json_depth: JsonInteger;
  /** Maximum JSON nodes. */
  json_nodes: JsonInteger;
  /** Maximum decoded binary key bytes. */
  key_bytes: JsonInteger;
  /** Maximum matching lexical candidates retained before ranking. */
  lexical_candidates: JsonInteger;
  /** Maximum durable documents inspected by one lexical retrieval. */
  lexical_documents: JsonInteger;
  /** Maximum matches returned by lexical or hybrid retrieval. */
  lexical_results: JsonInteger;
  /** Maximum requested lexical retrieval timeout. */
  lexical_timeout_ms: JsonInteger;
  /** Maximum normalized tokens processed by one lexical retrieval. */
  lexical_tokens: JsonInteger;
  /** Maximum matched records retained by one query. */
  matched_records: JsonInteger;
  /** Maximum aggregation metrics. */
  metrics: JsonInteger;
  /** Maximum canonical result-proof bytes before base64 transport. */
  proof_bytes: JsonInteger;
  /** Maximum requested query timeout. */
  query_timeout_ms: JsonInteger;
  /** Maximum complete JSON request bytes. */
  request_body_bytes: JsonInteger;
  /** Maximum time allowed to receive one complete JSON body. */
  request_body_timeout_ms: JsonInteger;
  /** Maximum serialized JSON response bytes. */
  response_bytes: JsonInteger;
  /** Maximum rows returned by one query page. */
  result_rows: JsonInteger;
  /** Maximum aggregate candidate key and vector bytes loaded. */
  retrieval_candidate_bytes: JsonInteger;
  /** Maximum vectors inspected by one exact retrieval. */
  retrieval_candidates: JsonInteger;
  /** Maximum canonical retrieval-proof bytes before base64 transport. */
  retrieval_proof_bytes: JsonInteger;
  /** Maximum matches returned by one retrieval. */
  retrieval_results: JsonInteger;
  /** Maximum requested retrieval timeout. */
  retrieval_timeout_ms: JsonInteger;
  /** Maximum records inspected globally by one query. */
  scanned_records: JsonInteger;
  /** Maximum explicit sort fields. */
  sort_fields: JsonInteger;
  /** Maximum dimensions in one durable vector space. */
  vector_dimensions: JsonInteger;
  /** Maximum downloadable canonical snapshot witness bytes. */
  witness_bytes: JsonInteger;
}

export type Blake3 = string;

export interface Build {
  builder: "partitioned-hnsw-v1";
  input_identity: Identity;
  aggregate_identity: Identity;
  expected_base_identity: Identity;
  expected_view_identity: Identity;
  published_base_identity: Identity;
  published_view_identity: Identity;
  vector_count: Positive;
  logical_partitions: 64;
  planned_workers: Positive;
  planned_memory_bytes: Positive;
  worker_batches: Positive;
  routing_policy: "metric-bound-adaptive-v1";
}

/** Public capability response. */
export interface CapabilitiesV1 {
  /** Fixed API path version. */
  api_version: string;
  /** Current numeric data-directory format. */
  disk_format_version: JsonInteger;
  /** Sorted implemented feature identifiers. */
  features: Array<string>;
  /** Effective policy limits visible to clients. */
  limits: ApiLimitsV1;
}

export type Class = "foreground-point" | "foreground-bounded" | "mutation" | "bulk" | "maintenance" | "recovery" | "administrative";

export interface ClassLimit {
  class: Class;
  compute_threads: JsonInteger;
  io_slots: JsonInteger;
  memory_bytes: JsonInteger;
}

/** Durable commit receipt. */
export interface CommitReceiptV1 {
  /** Commit-frame digest as hexadecimal. */
  commit_digest: string;
  /** Authoritative commit-frame sequence. */
  commit_sequence: JsonInteger;
  /** `committed` for a new commit or `existing` for an exact retry. */
  status: string;
  /** Canonical transaction digest as hexadecimal. */
  transaction_digest: string;
  /** UUID idempotency identifier. */
  transaction_id: string;
}

/** Ordered comparison operator. */
export type CompareOperatorV1 = "equal" | "not_equal" | "less" | "less_or_equal" | "greater" | "greater_or_equal";

export interface Consolidation {
  before_base_identity: Identity;
  before_view_identity: Identity;
  after_base_identity: Identity;
  after_view_identity: Identity;
  remaining_delta_records: 0;
  view_preserved: true;
  visible_result_identity: Identity;
  partitioned_base_preserved: true;
  routing_outcome_after: "selected-certified";
  total_partitions_after: JsonInteger;
}

export interface Counter {
  status: "measured" | "unsupported";
  value: JsonInteger | null;
  unit: string;
  provider: string;
  reason: string | null;
}

/** Logical continuation cursor. */
export interface CursorV1 {
  /** Final binary key tie-breaker as hexadecimal. */
  key_hex: string;
  /** Normalized sort values; JSON null represents missing/null. */
  sort_values: Array<JsonValue>;
}

/** Atomic durable lexical-index definition request. */
export interface DefineLexicalIndexRequestV1 {
  /** Immutable lexical-index definition. */
  lexical_index: LexicalIndexV1;
  /** Optional UUID idempotency key; a `UUIDv7` is generated when absent. */
  transaction_id?: string | null;
}

/** Atomic durable vector-space definition request. */
export interface DefineVectorSpaceRequestV1 {
  /** Optional UUID idempotency key; a `UUIDv7` is generated when absent. */
  transaction_id?: string | null;
  /** Immutable vector-space definition. */
  vector_space: VectorSpaceV1;
}

/** Atomic durable delete batch. */
export interface DeleteRequestV1 {
  /** Nonempty binary keys encoded as hexadecimal. */
  keys_hex: Array<string>;
  /** Optional UUID idempotency key; a `UUIDv7` is generated when absent. */
  transaction_id?: string | null;
}

/** Atomic durable vector deletion batch. */
export interface DeleteVectorsRequestV1 {
  /** Nonempty binary object keys encoded as hexadecimal. */
  keys_hex: Array<string>;
  /** Optional UUID idempotency key; a `UUIDv7` is generated when absent. */
  transaction_id?: string | null;
  /** Existing vector-space name. */
  vector_space: string;
}

export interface Delta {
  before_base_identity: Identity;
  before_view_identity: Identity;
  after_base_identity: Identity;
  after_view_identity: Identity;
  upserted_vectors: Positive;
  deleted_vectors: Positive;
  upserts_visible: true;
  deletes_hidden: true;
  visible_result_identity: Identity;
}

export type Digest = string;

/** Stable version 1 public error envelope. */
export interface ErrorV1 {
  /** Stable machine-readable error code. */
  code: string;
  /** Bounded human-readable diagnostic. */
  message: string;
  /** Generated request identifier also returned as a response header. */
  request_id: string;
}

export interface Eta {
  status: "pending" | "estimated" | "completed";
  estimated_remaining_nanos: null | JsonInteger;
}

/** Stable normal exact-retrieval abstention reason. */
export type ExactAbstentionReasonV1 = "no_candidates" | "below_threshold" | "ambiguous";

/** Stable exact-retrieval abstention evidence. */
export interface ExactAbstentionV1 {
  /** Best score when a candidate exists. */
  best_score_nanos?: JsonInteger | null;
  /** Stable reason. */
  reason: ExactAbstentionReasonV1;
  /** Runner-up score when one exists. */
  runner_up_score_nanos?: JsonInteger | null;
  /** Global candidates inspected. */
  scanned_candidates: JsonInteger;
}

/** One canonical exact-retrieval match. */
export interface ExactRetrievalMatchV1 {
  /** Binary object key encoded as hexadecimal. */
  key_hex: string;
  /** Canonical signed integer cosine score. */
  score_nanos: JsonInteger;
}

/** Complete durable exact-retrieval outcome. */
export type ExactRetrievalOutcomeV1 = {
  matches: Array<ExactRetrievalMatchV1>;
  scanned_candidates: JsonInteger;
  status: "matches";
} | {
  abstention: ExactAbstentionV1;
  status: "abstained";
};

/** Durable exact-retrieval request under reference semantics v2. */
export interface ExactRetrievalRequestV1 {
  /** Maximum returned matches. */
  limit: JsonInteger;
  /** Minimum canonical best/runner-up margin. */
  minimum_margin_nanos: JsonInteger;
  /** Inclusive minimum canonical cosine score. */
  minimum_score_nanos: JsonInteger;
  /** Canonical signed-Q15 query vector. */
  query: Array<JsonInteger>;
  /** Optional per-request timeout bounded by server policy. */
  timeout_ms?: JsonInteger | null;
  /** Existing vector-space name. */
  vector_space: string;
}

/** Proof-bearing durable exact-retrieval response. */
export interface ExactRetrievalResponseV1 {
  /** Complete matches or typed abstention. */
  outcome: ExactRetrievalOutcomeV1;
  /** Canonical retrieval proof and witness identity. */
  proof: RetrievalProofV1;
}

/** Versioned recursive filter expression. */
export type FilterV1 = {
  op: "match_all";
} | {
  op: "exists";
  path: Array<string>;
} | {
  op: "compare";
  operator: CompareOperatorV1;
  path: Array<string>;
  value: JsonValue;
} | {
  op: "prefix";
  path: Array<string>;
  prefix: JsonValue;
} | {
  needle: JsonValue;
  op: "contains";
  path: Array<string>;
} | {
  filters: Array<FilterV1>;
  op: "all";
} | {
  filters: Array<FilterV1>;
  op: "any";
} | {
  filter: FilterV1;
  op: "not";
};

export interface FinalReopen {
  base_identity: Identity;
  view_identity: Identity;
  delta_records: 0;
  view_preserved: true;
  visible_result_identity: Identity;
  routing_outcome: "selected-certified";
  total_partitions: JsonInteger;
}

/** Exact durable KV lookup. */
export interface GetRequestV1 {
  /** Nonempty binary key encoded as hexadecimal. */
  key_hex: string;
}

/** Proof-bearing exact lookup response. */
export interface GetResponseV1 {
  /** Whether the key exists at the proven checkpoint. */
  found: boolean;
  /** Complete result proof and witness identity. */
  proof: ProofV1;
  /** Present record, or `null` for proven absence. */
  record?: RecordV1 | null;
}

export type GitObject = string;

/** One aggregation group-key component preserving missing versus explicit null. */
export type GroupKeyValueV1 = {
  kind: "missing";
} | {
  kind: "value";
  value: JsonValue;
};

/** One deterministic aggregate group. */
export interface GroupResultV1 {
  /** Ordered group values with an explicit missing/null distinction. */
  key: Array<GroupKeyValueV1>;
  /** Metric results in request order. */
  metrics: Array<NamedMetricResultV1>;
}

/** Liveness or readiness response. */
export interface HealthV1 {
  /** `live` or `ready`. */
  status: string;
}

/** Both hybrid branches abstained normally. */
export interface HybridAbstentionV1 {
  /** Lexical branch absence. */
  lexical: HybridBranchAbsenceV1;
  /** Exact-vector branch absence. */
  vector: HybridBranchAbsenceV1;
}

/** Preserved reason for one absent hybrid branch. */
export type HybridBranchAbsenceV1 = "lexical_no_candidates" | "vector_no_candidates" | "vector_below_threshold" | "vector_ambiguous";

/** Full deterministic explanation for one hybrid result. */
export interface HybridExplanationV1 {
  /** One-based final rank. */
  final_rank: JsonInteger;
  /** Checked contribution sum. */
  fusion_score: JsonInteger;
  /** Integer lexical RRF contribution. */
  lexical_contribution: JsonInteger;
  /** One-based lexical rank when present. */
  lexical_rank?: JsonInteger | null;
  /** Canonical lexical score when present. */
  lexical_score_nanos?: JsonInteger | null;
  /** Integer vector RRF contribution. */
  vector_contribution: JsonInteger;
  /** One-based exact-vector rank when present. */
  vector_rank?: JsonInteger | null;
  /** Canonical exact-vector score when present. */
  vector_score_nanos?: JsonInteger | null;
}

/** One canonical hybrid retrieval match. */
export interface HybridRetrievalMatchV1 {
  /** Complete fusion explanation. */
  explanation: HybridExplanationV1;
  /** Binary object key encoded as hexadecimal. */
  key_hex: string;
}

/** Complete deterministic hybrid retrieval outcome. */
export type HybridRetrievalOutcomeV1 = {
  lexical_absence?: HybridBranchAbsenceV1 | null;
  matches: Array<HybridRetrievalMatchV1>;
  status: "matches";
  vector_absence?: HybridBranchAbsenceV1 | null;
} | {
  abstention: HybridAbstentionV1;
  status: "abstained";
};

/** Complete hybrid retrieval request under deterministic RRF semantics v1. */
export interface HybridRetrievalRequestV1 {
  /** Complete lexical branch request and candidate limit. */
  lexical: LexicalRetrievalRequestV1;
  /** Positive lexical RRF weight in `1..=1_000_000`. */
  lexical_weight: JsonInteger;
  /** Maximum final matches after deduplication and fusion. */
  limit: JsonInteger;
  /** Complete exact-vector branch request and candidate limit. */
  vector: ExactRetrievalRequestV1;
  /** Positive vector RRF weight in `1..=1_000_000`. */
  vector_weight: JsonInteger;
}

/** Proof-bearing deterministic hybrid retrieval response. */
export interface HybridRetrievalResponseV1 {
  /** Complete fused matches or typed abstention. */
  outcome: HybridRetrievalOutcomeV1;
  /** Canonical retrieval proof and witness identity. */
  proof: RetrievalProofV1;
}

export interface HyphaeNativeANNDurableLocalQualificationV1 {
  schema: "hyphae-native-ann-durable-qualification-v1";
  status: "diagnostic";
  source: {
    commit: Sha;
    tree: Sha;
    clean: true;
  };
  dataset: {
    generator: "hyphae-ann-durable-qualification-corpus-v2";
    digest: Identity;
    vectors: 512;
    dimension: JsonInteger;
    metric: "squared-l2" | "cosine" | "negative-dot";
  };
  build: Build;
  quality: null | Quality;
  lifecycle: {
    initial_reopen: null | InitialReopen;
    delta: null | Delta;
    consolidation: null | Consolidation;
    final_reopen: null | FinalReopen;
  };
  missing_gate_evidence: Array<"adaptive-routing-certification" | "consolidation-visibility" | "delta-visibility" | "durable-reopen" | "full-fanout-equality" | "post-consolidation-reopen" | "selected-recall-floor">;
  claims: [];
  closure_declared: false;
}

export interface HyphaeNativeHardwareCalibrationV1 {
  schema: "hyphae-native-hardware-calibration-v1";
  mode: "quick" | "thorough";
  status: "stable" | "unstable" | "rejected";
  accepted_for_scheduling: boolean;
  cache_status: "disabled" | "hit" | "miss";
  elapsed_ms: JsonInteger;
  identity: {
    hardware_fingerprint: Digest;
    kernel_release: string;
    filesystem: OptionalString;
    compiler_identity: string;
    hyphae_build_identity: string;
    executable_blake3: Digest;
    cache_key: Digest;
  };
  policy: {
    minimum_duration_ms: JsonInteger;
    maximum_duration_ms: JsonInteger;
    warmup_batches: JsonInteger;
    samples_per_measurement: JsonInteger;
    target_sample_duration_ms: JsonInteger;
    maximum_relative_mad_ppm: JsonInteger;
    maximum_relative_range_ppm: JsonInteger;
  };
  feature_detection: {
    instruction_sets: UniqueStrings;
    differential_tests_passed: boolean;
  };
  measurements: Array<Measurement>;
  selected_kernels: Array<{
    primitive: string;
    input_size: JsonInteger;
    input_unit: string;
    variant: string;
    reason: string;
  }>;
  thread_scaling: {
    binding: "unbound" | "linux-sched-affinity" | "inconsistent";
    physical_core_boundary: JsonInteger;
    logical_processor_boundary: JsonInteger;
    measured_thread_counts: Array<JsonInteger>;
    status: "stable" | "unavailable";
    physical_peak_threads: JsonInteger | null;
    physical_peak_bytes_per_second: JsonInteger | null;
    smt_peak_threads: JsonInteger | null;
    smt_peak_bytes_per_second: JsonInteger | null;
    smt_to_physical_throughput_ppm: JsonInteger | null;
    smt_recommended: boolean;
    recommended_worker_count: JsonInteger | null;
    recommendation: string;
  };
  io_scaling: {
    binding: "buffered-sync-workers";
    measured_queue_depths: Array<JsonInteger>;
    status: "stable" | "unavailable";
    peak_queue_depth: JsonInteger | null;
    peak_bytes_per_second: JsonInteger | null;
    recommended_io_slots: JsonInteger | null;
    recommendation: string;
  };
  coverage: {
    measured: UniqueStrings;
    unsupported: Array<{
      primitive: string;
      reason: string;
    }>;
  };
  claims: Array<JsonValue>;
}

export interface HyphaeNativeHardwareProfileV1 {
  schema: "hyphae-native-hardware-profile-v1";
  fingerprint: Digest;
  cpu: {
    architecture: string;
    logical_processors_available: JsonInteger;
    physical_cores_visible: OptionalPositiveInteger;
    smt_threads_per_core: OptionalPositiveInteger;
    sockets_visible: OptionalPositiveInteger;
    numa_nodes_visible: OptionalPositiveInteger;
    affinity: string;
    quota_millicores: OptionalPositiveInteger;
    instruction_sets: UniqueStrings;
    frequency_governors: UniqueStrings;
    caches: Array<{
      level: JsonInteger;
      kind: string;
      size_bytes: JsonInteger;
      line_size_bytes: OptionalPositiveInteger;
      shared_cpu_list: string;
    }>;
    processor_topology: Array<{
      logical_id: JsonInteger;
      core_id: JsonInteger;
      socket_id: JsonInteger;
      numa_node_id: JsonInteger | null;
      thread_siblings: string;
    }>;
  };
  memory: {
    total_bytes: OptionalPositiveInteger;
    available_bytes: OptionalNonnegativeInteger;
    page_size_bytes: OptionalPositiveInteger;
    huge_page_size_bytes: OptionalPositiveInteger;
    huge_pages_total: OptionalNonnegativeInteger;
    numa_nodes: Array<{
      id: JsonInteger;
      cpu_list: string;
      total_bytes: OptionalPositiveInteger;
      available_bytes: OptionalNonnegativeInteger;
    }>;
  };
  storage: {
    path: string;
    filesystem: OptionalString;
    device: OptionalString;
    mount_options: UniqueStrings;
    rotational: boolean | null;
    queue_depth: OptionalNonnegativeInteger;
    discard_max_bytes: OptionalNonnegativeInteger;
  };
  operating_system: {
    family: string;
    kernel_release: string;
    virtualization: string;
    local_transports: UniqueStrings;
  };
}

export interface HyphaeNativePerformanceProgressV1 {
  schema: "hyphae-native-performance-progress-v1";
  source_commit: Sha1;
  source_tree: Sha1;
  dataset_digest: Sha256;
  operation: string;
  stage: string;
  sequence: JsonInteger;
  completed_units: JsonInteger;
  total_units: JsonInteger;
  unit: string;
  elapsed_nanos: JsonInteger;
  status: "running" | "completed";
  checkpoint_digest: null | Sha256;
  details: {
    eta: Eta;
  };
}

export interface HyphaeNativePerformanceReceiptV1 {
  schema: "hyphae-native-performance-receipt-v1";
  status: "passed";
  evidence_class: "diagnostic-baseline" | "regression-candidate" | "qualification-candidate";
  source: {
    commit: Sha1;
    tree: Sha1;
    binary_sha256: Sha256;
    profile_sha256: Sha256;
    clean: boolean;
  };
  environment: {
    platform: string;
    target: string;
    os: string;
    compiler: string;
    build_profile: string;
    hardware_fingerprint: Sha256;
    dedicated: boolean;
    virtualization: string;
    topology: string;
    affinity: string;
  };
  workload: {
    class: "foreground-point" | "foreground-bounded" | "mutation" | "bulk" | "maintenance" | "recovery" | "administrative";
    engines: Array<"sql" | "structures" | "lexical" | "vector" | "wal" | "storage" | "convergence">;
    operation: string;
    parameters_sha256: Sha256;
  };
  dataset: {
    source_commit: Sha1;
    generator: string;
    digest: Sha256;
    records: NonnegativeInteger;
    bytes: NonnegativeInteger;
  };
  measurement: {
    observations: JsonInteger;
    warmup: NonnegativeInteger;
    concurrency: JsonInteger;
    state: "warm" | "cold-first-touch";
    background_mode: "control" | "interference";
    elapsed_nanos: JsonInteger;
    clock_totals_nanos: {
      admission: NonnegativeInteger;
      queueing: NonnegativeInteger;
      parse_bind_plan: NonnegativeInteger;
      engine_execution: NonnegativeInteger;
      cross_engine_fusion: NonnegativeInteger;
      wal_append: NonnegativeInteger;
      physical_synchronization: NonnegativeInteger;
      transport: NonnegativeInteger;
      result_proof_encoding: NonnegativeInteger;
      unattributed: NonnegativeInteger;
    };
  };
  counters: {
    cpu_time: Counter;
    cpu_cycles: Counter;
    instructions: Counter;
    cache_misses: Counter;
    context_switches: Counter;
    page_faults: Counter;
    allocations: Counter;
    peak_rss: Counter;
    bytes_read: Counter;
    bytes_written: Counter;
  };
  correctness: {
    status: "passed";
    oracle: string;
    result_digest: Sha256;
  };
  claims: Array<JsonValue>;
  closure_declared: false;
}

export interface HyphaeNativePerformanceSuiteV1 {
  schema: "hyphae-native-performance-suite-v1";
  status: "passed";
  suite_profile_sha256: Sha256;
  source_commit: Sha1;
  source_tree: Sha1;
  binary_sha256: Sha256;
  clean: boolean;
  hardware_fingerprint: Sha256;
  receipts: Array<HyphaeNativePerformanceReceiptV1>;
  claims: [];
  closure_declared: false;
}

export interface HyphaeNativePersistentExecutionTopologyV1 {
  schema: "hyphae-native-execution-topology-v1";
  hardware_fingerprint: string;
  schedulable_compute_threads: JsonInteger;
  hard_affinity: boolean;
  numa_steal_policy: NumaStealPolicy;
  pools: Array<Pool>;
}

export interface HyphaeNativeResourceGovernorPolicyV1 {
  schema: "hyphae-native-governor-policy-v1";
  mode: "latency" | "bulk" | "mixed";
  hardware_fingerprint: Digest;
  calibration_cache_key: Digest;
  calibrated_worker_limit: JsonInteger;
  reserved_system_threads: JsonInteger;
  schedulable_compute_threads: JsonInteger;
  io_slots: JsonInteger;
  memory_bytes: JsonInteger;
  memory_headroom_percent: 15;
  admission_queue_capacity: JsonInteger;
  foreground_burst_limit: 16;
  class_limits: Array<ClassLimit>;
}

export interface HyphaeNativeSchedulerAuthorityV1 {
  schema: "hyphae-native-scheduler-authority-v1";
  source_commit: string;
  source_tree: string;
  executable_blake3: Blake3;
  mode: "latency" | "bulk" | "mixed";
  hardware_fingerprint: Blake3;
  calibration_cache_key: Blake3;
  input_canonical_sha256: {
    profile: Sha256;
    calibration: Sha256;
    policy: Sha256;
    topology: Sha256;
  };
  calibrated_worker_limit: JsonInteger;
  schedulable_compute_threads: JsonInteger;
  io_slots: JsonInteger;
  memory_bytes: JsonInteger;
  numa_pools: Array<JsonInteger | null>;
  hard_affinity: boolean;
  numa_steal_policy_schema: "hyphae-native-numa-steal-policy-v1";
  numa_steal_status: "not-applicable" | "disabled" | "calibrated";
  numa_steal_thresholds: Array<{
    worker_numa_node_id: JsonInteger;
    home_numa_node_id: JsonInteger;
    remote_to_local_latency_ppm: JsonInteger;
    steal_after_nanoseconds: JsonInteger;
  }>;
  status: "verified";
  claims: Array<JsonValue>;
}

/** Diagnostic-only evidence. Source commit/tree come from an external exact-source authority; producer_executable_blake3 binds the independently hashed producer bytes. This schema never grants scheduling, governor, cache, G7, or closure authority. */
export interface HyphaeNativeThreadScalingCalibrationDiagnosticV1 {
  schema: "hyphae-native-hardware-calibration-diagnostic-v1";
  authority: false;
  evidence_class: "diagnostic-only";
  claims: Array<JsonValue>;
  closure_declared: false;
  source: {
    commit: GitObject;
    tree: GitObject;
  };
  platform: string;
  identity: {
    hardware_fingerprint: Digest;
    producer_executable_blake3: Digest;
    compiler_identity: string;
    hyphae_build_identity: string;
  };
  policy: {
    mode: "thorough";
    warmup_batches: 4;
    samples_per_measurement: 31;
    target_sample_duration_ms: 225;
    maximum_relative_mad_ppm: 40000;
    operation_calibration_target_lower_ppm: 900000;
    operation_calibration_target_upper_ppm: 1100000;
    operation_calibration_confirmations: 3;
    operation_calibration_max_refinements: 6;
  };
  surface: {
    primitive: "thread-scaling-memory-scan";
    binding: "linux-sched-affinity" | "unbound";
    worker_points: Array<WorkerPoint>;
  };
}

export interface HyphaeNativeVectorBulkBuildBakeoffV1 {
  schema: "hyphae-native-vector-bulk-bakeoff-v1";
  status: "diagnostic";
  source_commit: string;
  hardware_fingerprint: Digest;
  governor_calibration_cache_key: Digest;
  dataset: {
    generator: "hyphae-partitioned-hnsw-bakeoff-v1";
    digest: Digest;
    vectors: Positive;
    dimension: JsonInteger;
    metric: "squared-l2";
    corpus_construction_nanos: Nonnegative;
  };
  build: {
    requested_partitions: Positive;
    effective_partitions: Positive;
    serial_hnsw_nanos: Nonnegative;
    serial_partitioned_nanos: Nonnegative;
    parallel_partitioned_nanos: Nonnegative;
    planned_compute_threads: Positive;
    planned_memory_bytes: Positive;
    worker_batches: Positive;
    single_build_identity: Digest;
    partitioned_build_identity: Digest;
    deterministic_across_serial_and_parallel: true;
    durable_publication: false;
  };
  quality: {
    queries: Positive;
    k: Positive;
    ef_search: Positive;
    selected_partitions: Positive;
    single_hnsw_recall_ppm: Recall;
    partitioned_hnsw_recall_ppm: Recall;
    selected_partition_recall_ppm: Recall;
    minimum_single_query_recall_ppm: Recall;
    minimum_partitioned_query_recall_ppm: Recall;
    minimum_selected_query_recall_ppm: Recall;
    single_query_batch_nanos: Nonnegative;
    partitioned_query_batch_nanos: Nonnegative;
    selected_query_batch_nanos: Nonnegative;
    oracle: "partitioned-exact-flat-canonical-top-k-v1";
  };
  missing_gate_evidence: Array<string>;
  claims: [];
  closure_declared: false;
}

export type Identity = string;

export interface InitialReopen {
  base_identity: Identity;
  view_identity: Identity;
  selected_result_identity: Identity;
}

/** Stable normal lexical abstention reason. */
export type LexicalAbstentionReasonV1 = "no_candidates";

/** Stable lexical abstention evidence. */
export interface LexicalAbstentionV1 {
  /** Canonical unique normalized query tokens. */
  query_tokens: Array<string>;
  /** Stable reason. */
  reason: LexicalAbstentionReasonV1;
  /** Durable documents inspected. */
  scanned_documents: JsonInteger;
}

/** One configured-field contribution to a lexical term score. */
export interface LexicalFieldContributionV1 {
  /** Normalized field token length. */
  field_length: JsonInteger;
  /** Canonical exact field path. */
  path: Array<string>;
  /** Raw term frequency in this field. */
  term_frequency: JsonInteger;
}

/** One configured field in an immutable lexical-index definition. */
export interface LexicalFieldV1 {
  /** Nonempty exact object path. */
  path: Array<string>;
  /** Positive field weight in millionths. */
  weight_micros: JsonInteger;
}

/** One immutable provider-free lexical-index definition. */
export interface LexicalIndexV1 {
  /** Nonempty unique fields; the server canonicalizes path order. */
  fields: Array<LexicalFieldV1>;
  /** Stable lowercase index name. */
  name: string;
}

/** One canonical lexical retrieval match. */
export interface LexicalRetrievalMatchV1 {
  /** Binary object key encoded as hexadecimal. */
  key_hex: string;
  /** Canonical BM25F score in nanos. */
  score_nanos: JsonInteger;
  /** Deterministic per-term explanation. */
  terms: Array<LexicalTermContributionV1>;
}

/** Complete durable lexical retrieval outcome. */
export type LexicalRetrievalOutcomeV1 = {
  matched_documents: JsonInteger;
  matches: Array<LexicalRetrievalMatchV1>;
  query_tokens: Array<string>;
  scanned_documents: JsonInteger;
  status: "matches";
} | {
  abstention: LexicalAbstentionV1;
  status: "abstained";
};

/** Durable provider-free lexical retrieval request under semantics v1. */
export interface LexicalRetrievalRequestV1 {
  /** Existing lexical-index name. */
  lexical_index: string;
  /** Maximum returned matches. */
  limit: JsonInteger;
  /** UTF-8 query analyzed by tokenizer v1. */
  query: string;
  /** Optional per-request timeout bounded by server policy. */
  timeout_ms?: JsonInteger | null;
}

/** Proof-bearing durable lexical retrieval response. */
export interface LexicalRetrievalResponseV1 {
  /** Complete matches or typed abstention. */
  outcome: LexicalRetrievalOutcomeV1;
  /** Canonical retrieval proof and witness identity. */
  proof: RetrievalProofV1;
}

/** One canonical query-term contribution to a lexical result. */
export interface LexicalTermContributionV1 {
  /** Corpus document frequency. */
  document_frequency: JsonInteger;
  /** Configured fields in canonical path order. */
  fields: Array<LexicalFieldContributionV1>;
  /** Quantized BM25F contribution. */
  score_nanos: JsonInteger;
  /** Canonical tokenizer-v1 token. */
  token: string;
}

export interface Measurement {
  primitive: string;
  variant: string;
  input_size: JsonInteger;
  input_unit: string;
  bytes_per_operation: JsonInteger;
  operations_per_sample: JsonInteger;
  maximum_operations_per_sample: JsonInteger;
  sample_count: JsonInteger;
  statistics: {
    unit: "picoseconds_per_operation";
    minimum: JsonInteger;
    median: JsonInteger;
    maximum: JsonInteger;
    median_absolute_deviation: JsonInteger;
    relative_mad_ppm: JsonInteger;
    relative_range_ppm: JsonInteger;
    median_bytes_per_second: JsonInteger | null;
  };
  correctness: {
    status: "passed" | "failed";
    result_digest_blake3: Digest;
    reference_digest_blake3: Digest;
  };
  status: "stable" | "unstable" | "rejected";
}

/** Versioned aggregate metric output. */
export type MetricValueV1 = {
  kind: "count";
  value: JsonInteger;
} | {
  kind: "integer";
  value?: string | null;
} | {
  kind: "value";
  value?: JsonValue;
};

/** Named aggregate result. */
export interface NamedMetricResultV1 {
  /** Metric name from the request. */
  name: string;
  /** Typed metric value. */
  result: MetricValueV1;
}

/** One named aggregation metric. */
export type NamedMetricV1 = {
  metric: "count";
  name: string;
} | {
  metric: "sum";
  name: string;
  path: Array<string>;
} | {
  metric: "min";
  name: string;
  path: Array<string>;
} | {
  metric: "max";
  name: string;
  path: Array<string>;
};

export type Nonnegative = JsonInteger;

export type NonnegativeInteger = JsonInteger;

/** Wire null placement. */
export type NullPlacementV1 = "first" | "last";

export type NullableId = JsonInteger | null;

export interface NumaStealPolicy {
  schema: "hyphae-native-numa-steal-policy-v1";
  calibration_cache_key: string;
  status: "not-applicable" | "disabled" | "calibrated";
  working_set_bytes: 8388608;
  foreground_burst_limit: 16;
  pools: Array<NumaStealPool>;
}

export interface NumaStealPool {
  worker_numa_node_id: NullableId;
  steal_targets: Array<NumaStealTarget>;
}

export interface NumaStealTarget {
  home_numa_node_id: JsonInteger;
  remote_to_local_latency_ppm: JsonInteger;
  steal_after_nanoseconds: JsonInteger;
}

export type OptionalNonnegativeInteger = null | JsonInteger;

export type OptionalPositiveInteger = null | JsonInteger;

export type OptionalString = null | string;

export interface Pool {
  numa_node_id: NullableId;
  workers: Array<Worker>;
}

export type Positive = JsonInteger;

/** Portable result proof plus its downloadable witness reference. */
export interface ProofV1 {
  /** Caller-pinnable anchor digest as hexadecimal. */
  anchor_digest: string;
  /** Commit digest as hexadecimal, absent for empty history. */
  checkpoint_digest?: string | null;
  /** Snapshot/log checkpoint sequence. */
  checkpoint_sequence: JsonInteger;
  /** Canonical `.hyproof` bytes in standard padded base64. */
  data: string;
  /** Fixed encoding identifier `base64`. */
  encoding: string;
  /** Canonical proof digest as hexadecimal. */
  proof_digest: string;
  /** Canonical logical snapshot digest as hexadecimal. */
  snapshot_digest: string;
  /** Authenticated endpoint for the complete offline witness. */
  witness: WitnessV1;
}

/** Atomic durable put batch. */
export interface PutRequestV1 {
  /** Nonempty atomic record batch. */
  records: Array<RecordV1>;
  /** Optional UUID idempotency key; a `UUIDv7` is generated when absent. */
  transaction_id?: string | null;
}

/** Atomic durable vector upsert batch. */
export interface PutVectorsRequestV1 {
  /** Optional UUID idempotency key; a `UUIDv7` is generated when absent. */
  transaction_id?: string | null;
  /** Existing vector-space name. */
  vector_space: string;
  /** Nonempty atomic vector batch. */
  vectors: Array<VectorV1>;
}

export interface Quality {
  query_set_identity: Identity;
  queries: Positive;
  k: Positive;
  ef_search: Positive;
  selected_partitions: 32;
  certified_selected_queries: Positive;
  full_fanout_fallback_queries: 0;
  maximum_searched_partitions: 32;
  selected_query_recall_ppm: JsonInteger;
  minimum_selected_query_recall_ppm: JsonInteger;
  oracle_result_identity: Identity;
  default_result_identity: Identity;
  full_fanout_result_identity: Identity;
  selected_result_identity: Identity;
  full_fanout_equals_default: true;
}

/** Complete version 1 structured query request. */
export interface QueryRequestV1 {
  /** Optional global or grouped aggregation. */
  aggregation?: AggregationPlanV1 | null;
  /** Optional logical continuation cursor. */
  cursor?: CursorV1 | null;
  /** Recursive filter; defaults to match-all. */
  filter?: FilterV1;
  /** Final page size. */
  limit: JsonInteger;
  /** Deterministic sort fields. */
  sort?: Array<SortFieldV1>;
  /** Requested cooperative query timeout. */
  timeout_ms?: JsonInteger | null;
}

/** Proof-bearing structured query response. */
export interface QueryResponseV1 {
  /** Optional complete aggregation. */
  aggregation?: AggregationResultV1 | null;
  /** Records matching before pagination. */
  matched_records: JsonInteger;
  /** Logical continuation cursor when more rows exist. */
  next_cursor?: CursorV1 | null;
  /** Complete result proof and witness identity. */
  proof: ProofV1;
  /** Final page rows. */
  rows: Array<RecordV1>;
  /** Records inspected globally. */
  scanned_records: JsonInteger;
}

export type Recall = JsonInteger;

/** One structured record on the wire. */
export interface RecordV1 {
  /** Nonempty binary key encoded as hexadecimal. */
  key_hex: string;
  /** Natural JSON structured value with the reserved bytes envelope. */
  value: JsonValue;
}

/** Portable retrieval proof plus its downloadable witness reference. */
export interface RetrievalProofV1 {
  /** Caller-pinnable retrieval anchor digest as hexadecimal. */
  anchor_digest: string;
  /** Commit digest as hexadecimal, absent for empty history. */
  checkpoint_digest?: string | null;
  /** Snapshot/log checkpoint sequence. */
  checkpoint_sequence: JsonInteger;
  /** Canonical `.hyrproof` bytes in standard padded base64. */
  data: string;
  /** Fixed encoding identifier `base64`. */
  encoding: string;
  /** Canonical proof digest as hexadecimal. */
  proof_digest: string;
  /** Canonical logical snapshot digest as hexadecimal. */
  snapshot_digest: string;
  /** Authenticated endpoint for the complete offline witness. */
  witness: WitnessV1;
}

export type Sha = string;

export type Sha1 = string;

export type Sha256 = string;

/** Wire sort direction. */
export type SortDirectionV1 = "ascending" | "descending";

/** One versioned sort field. */
export interface SortFieldV1 {
  /** Value direction. */
  direction: SortDirectionV1;
  /** Explicit missing/null placement. */
  nulls: NullPlacementV1;
  /** Exact object path. */
  path: Array<string>;
}

export interface Statistics {
  unit: "picoseconds_per_operation";
  minimum: JsonInteger;
  median: JsonInteger;
  maximum: JsonInteger;
  median_absolute_deviation: JsonInteger;
  relative_mad_ppm: JsonInteger;
  relative_range_ppm: JsonInteger;
  median_bytes_per_second: JsonInteger;
}

export type UniqueStrings = Array<string>;

/** Canonical durable vector metric. */
export type VectorMetricV1 = "cosine_q15_nanos";

/** One immutable durable vector-space definition. */
export interface VectorSpaceV1 {
  /** Fixed number of signed-Q15 elements. */
  dimension: JsonInteger;
  /** Canonical scoring metric. */
  metric: VectorMetricV1;
  /** Stable lowercase vector-space name. */
  name: string;
}

/** One canonical signed-Q15 vector on the wire. */
export interface VectorV1 {
  /** Nonempty binary object key encoded as hexadecimal. */
  key_hex: string;
  /** Signed-Q15 elements whose length must match the space dimension. */
  values: Array<JsonInteger>;
}

/** Download reference for one canonical logical snapshot. */
export interface WitnessV1 {
  /** Complete snapshot file length. */
  file_bytes: JsonInteger;
  /** Versioned relative HTTP path. */
  path: string;
}

export interface Worker {
  worker_index: JsonInteger;
  numa_node_id: NullableId;
  logical_processor_id: NullableId;
  socket_id: NullableId;
  core_id: NullableId;
  smt_rank: NullableId;
}

export interface WorkerPoint {
  worker_count: JsonInteger;
  variant: string;
  bytes_per_operation: JsonInteger;
  operations_per_sample: JsonInteger;
  maximum_operations_per_sample: 1048576;
  batch_calibration_status: "converged" | "not-converged";
  samples_picoseconds_per_operation: Array<JsonInteger>;
  statistics: Statistics;
  correctness: {
    status: "passed";
    result_digest_blake3: Digest;
    reference_digest_blake3: Digest;
  };
  status: "stable" | "unstable";
}
