#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Verify publishable crates from their exact generated package contents."""

from __future__ import annotations

import json
import shutil
import subprocess
import sys
import tarfile
import tempfile
import tomllib
from pathlib import Path, PurePosixPath

if __package__ in {None, ""}:
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from tools.check_crate_packages import validate_release_graph
from tools.check_registry_publish import validate_publish_authority


ROOT = Path(__file__).resolve().parents[1]
RELEASE_CONFIG = ROOT / "config" / "crates-io-release.json"
WORKSPACE_LOCKFILE = ROOT / "Cargo.lock"


def verification_manifest(packages: tuple[str, ...], version: str) -> str:
    members = [f'    "packages/{package}-{version}",' for package in packages]
    patches = [
        f'"{package}" = {{ path = "packages/{package}-{version}" }}'
        for package in packages
    ]
    return "\n".join(
        [
            "# Generated by tools/verify_crate_packages.py.",
            "[workspace]",
            'resolver = "2"',
            "members = [",
            *members,
            "]",
            "",
            "[patch.crates-io]",
            *patches,
            "",
        ]
    )


def validate_local_resolution(
    metadata: dict[str, object],
    packages: tuple[str, ...],
    package_roots: dict[str, Path],
) -> list[str]:
    """Reject any release crate resolved outside its extracted package."""
    expected = set(packages)
    resolved: dict[str, list[dict[str, object]]] = {name: [] for name in packages}
    metadata_packages = metadata.get("packages", [])
    if not isinstance(metadata_packages, list):
        return ["verification metadata packages are malformed"]
    for package in metadata_packages:
        if isinstance(package, dict) and package.get("name") in expected:
            resolved[str(package["name"])].append(package)

    failures: list[str] = []
    for name in packages:
        candidates = resolved[name]
        if len(candidates) != 1:
            failures.append(
                f"{name}: verification resolved {len(candidates)} package sources"
            )
            continue
        package = candidates[0]
        manifest = package.get("manifest_path")
        if package.get("source") is not None:
            failures.append(f"{name}: verification resolved a registry package")
        if (
            not isinstance(manifest, str)
            or Path(manifest).resolve().parent != package_roots[name]
        ):
            failures.append(f"{name}: verification did not use the extracted package")
    return failures


def locked_registry_packages(lockfile: Path) -> set[tuple[str, str]]:
    """Return every (name, version) the workspace lockfile pins to a registry."""
    document = tomllib.loads(lockfile.read_text(encoding="utf-8"))
    entries = document.get("package", [])
    if not isinstance(entries, list):
        raise ValueError(f"{lockfile.name}: package table is malformed")
    locked: set[tuple[str, str]] = set()
    for entry in entries:
        if not isinstance(entry, dict) or "source" not in entry:
            continue
        name, version = entry.get("name"), entry.get("version")
        if not isinstance(name, str) or not isinstance(version, str):
            raise ValueError(f"{lockfile.name}: package entry is malformed")
        locked.add((name, version))
    return locked


def validate_locked_registry_resolution(
    metadata: dict[str, object],
    packages: tuple[str, ...],
    locked: set[tuple[str, str]],
) -> list[str]:
    """Reject any registry package resolved at a version the lockfile did not pin.

    The verification workspace is seeded with the workspace lockfile, so a
    registry release published after the lockfile was written can never enter
    the packaged build: Cargo may only drop lockfile entries the packaged
    crates do not need, never pick a version the lockfile does not name.
    """
    expected = set(packages)
    metadata_packages = metadata.get("packages", [])
    if not isinstance(metadata_packages, list):
        return ["verification metadata packages are malformed"]
    failures: list[str] = []
    for package in metadata_packages:
        if not isinstance(package, dict) or package.get("name") in expected:
            continue
        name, version = package.get("name"), package.get("version")
        if package.get("source") is None:
            failures.append(f"{name}: verification resolved a non-registry dependency")
            continue
        if (name, version) not in locked:
            failures.append(
                f"{name} {version}: verification resolved a registry copy absent from Cargo.lock"
            )
    return sorted(failures)


def extract_crate(
    archive_path: Path, destination: Path, package: str, version: str
) -> Path:
    prefix = f"{package}-{version}"
    package_root = (destination / prefix).resolve()
    with tarfile.open(archive_path, "r:gz") as archive:
        members = archive.getmembers()
        for member in members:
            relative = PurePosixPath(member.name)
            if (
                relative.is_absolute()
                or ".." in relative.parts
                or relative.parts[:1] != (prefix,)
                or not (member.isfile() or member.isdir())
            ):
                raise ValueError(f"{package}: package archive contains an unsafe entry")
        archive.extractall(destination, members=members, filter="data")
    if not (package_root / "Cargo.toml").is_file():
        raise ValueError(f"{package}: package archive lacks Cargo.toml")
    return package_root


def run_json(root: Path, *arguments: str) -> dict[str, object]:
    completed = subprocess.run(
        arguments,
        cwd=root,
        check=True,
        stdout=subprocess.PIPE,
        text=True,
        timeout=1800,
    )
    value = json.loads(completed.stdout)
    if not isinstance(value, dict):
        raise ValueError(f"{' '.join(arguments)} returned non-object JSON")
    return value


def main() -> int:
    try:
        release = json.loads(RELEASE_CONFIG.read_text(encoding="utf-8"))
        metadata = run_json(
            ROOT, "cargo", "metadata", "--no-deps", "--format-version", "1"
        )
        metadata_packages = metadata["packages"]
        if not isinstance(metadata_packages, list):
            raise ValueError("cargo metadata packages are malformed")
        cargo_packages = {
            package["name"]: package
            for package in metadata_packages
            if isinstance(package, dict) and isinstance(package.get("name"), str)
        }
        publishable = tuple(
            package["name"]
            for package in metadata_packages
            if isinstance(package, dict) and package.get("publish") != []
        )
        packages, failures = validate_release_graph(
            release, cargo_packages, publishable
        )
        failures.extend(validate_publish_authority("crates-io", ROOT, dry_run=True))
        if failures:
            raise ValueError("; ".join(failures))

        version = release["version"]
        with tempfile.TemporaryDirectory(prefix="hyphae-crate-packages-") as directory:
            temporary = Path(directory)
            package_target = temporary / "package-target"
            verification_root = temporary / "verification"
            extracted = verification_root / "packages"
            extracted.mkdir(parents=True)
            package_roots: dict[str, Path] = {}

            # One invocation packages every publication crate together, so
            # Cargo resolves exact internal dependencies against the crates
            # packaged in the same run. Per-crate invocations resolve against
            # the live registry index and fail while the candidate version is
            # deliberately unpublished.
            package_selectors: list[str] = []
            for package in packages:
                package_selectors.extend(("-p", package))
            subprocess.run(
                [
                    "cargo",
                    "package",
                    "--locked",
                    "--no-verify",
                    "--allow-dirty",
                    *package_selectors,
                    "--target-dir",
                    str(package_target),
                ],
                cwd=ROOT,
                check=True,
                timeout=1800,
            )
            for package in packages:
                archive = package_target / "package" / f"{package}-{version}.crate"
                if not archive.is_file():
                    raise ValueError(
                        f"{package}: cargo package did not produce {archive.name}"
                    )
                package_roots[package] = extract_crate(
                    archive, extracted, package, version
                )

            (verification_root / "Cargo.toml").write_text(
                verification_manifest(packages, version), encoding="utf-8"
            )
            # Seed the verification workspace with the exact workspace lockfile:
            # Cargo keeps every pinned version the packaged crates need and only
            # prunes the entries they do not, so the registry index state at
            # verification time cannot change what is built.
            shutil.copyfile(WORKSPACE_LOCKFILE, verification_root / "Cargo.lock")
            locked = locked_registry_packages(WORKSPACE_LOCKFILE)
            resolved = run_json(
                verification_root,
                "cargo",
                "metadata",
                "--format-version",
                "1",
            )
            failures = validate_local_resolution(resolved, packages, package_roots)
            failures.extend(
                validate_locked_registry_resolution(resolved, packages, locked)
            )
            if failures:
                raise ValueError("; ".join(failures))
            subprocess.run(
                [
                    "cargo",
                    "check",
                    "--workspace",
                    "--locked",
                    "--target-dir",
                    str(temporary / "check-target"),
                ],
                cwd=verification_root,
                check=True,
                timeout=1800,
            )
    except (OSError, ValueError, KeyError, TypeError, json.JSONDecodeError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 1
    except subprocess.CalledProcessError as error:
        print(f"error: command failed with exit code {error.returncode}", file=sys.stderr)
        return error.returncode or 1

    print(
        f"crate package verification passed: {len(packages)} exact packages at {version}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
