# SPDX-License-Identifier: Apache-2.0
# @generated by tools/generate_sdk_models.py; do not edit.
from __future__ import annotations

from typing import Literal, Never, NotRequired, TypeAlias, TypedDict

CONTRACT_SHA256 = "fb7195bcd2d16117b0b5fd86f032db292870548c8095532d984ae583448e0656"

JsonValue: TypeAlias = (
    None | bool | int | str | list["JsonValue"] | dict[str, "JsonValue"]
)

class AggregationPlanV1(TypedDict):
    """Optional grouped aggregation plan."""
    group_by: list[list[str]]
    metrics: list[NamedMetricV1]

class AggregationResultV1(TypedDict):
    """Complete aggregation response."""
    grouped: bool
    groups: list[GroupResultV1]

class ApiLimitsV1(TypedDict):
    """Public server policy limits."""
    aggregation_groups: int
    batch_items: int
    concurrent_operations: int
    document_bytes: int
    filter_depth: int
    filter_nodes: int
    group_fields: int
    json_depth: int
    json_nodes: int
    key_bytes: int
    lexical_candidates: int
    lexical_documents: int
    lexical_results: int
    lexical_timeout_ms: int
    lexical_tokens: int
    matched_records: int
    metrics: int
    proof_bytes: int
    query_timeout_ms: int
    request_body_bytes: int
    request_body_timeout_ms: int
    response_bytes: int
    result_rows: int
    retrieval_candidate_bytes: int
    retrieval_candidates: int
    retrieval_proof_bytes: int
    retrieval_results: int
    retrieval_timeout_ms: int
    scanned_records: int
    sort_fields: int
    vector_dimensions: int
    witness_bytes: int

class Build(TypedDict):
    builder: Literal["partitioned-hnsw-v1"]
    input_identity: Identity
    aggregate_identity: Identity
    expected_base_identity: Identity
    expected_view_identity: Identity
    published_base_identity: Identity
    published_view_identity: Identity
    vector_count: Positive
    logical_partitions: Literal[64]
    planned_workers: Positive
    planned_memory_bytes: Positive
    worker_batches: Positive
    routing_policy: Literal["metric-bound-adaptive-v1"]

class CapabilitiesV1(TypedDict):
    """Public capability response."""
    api_version: str
    disk_format_version: int
    features: list[str]
    limits: ApiLimitsV1

ClassLimit = TypedDict(
    "ClassLimit",
    {
        "class": "Class",
        "compute_threads": "int",
        "io_slots": "int",
        "memory_bytes": "int",
    },
)

class CommitReceiptV1(TypedDict):
    """Durable commit receipt."""
    commit_digest: str
    commit_sequence: int
    status: str
    transaction_digest: str
    transaction_id: str

class Consolidation(TypedDict):
    before_base_identity: Identity
    before_view_identity: Identity
    after_base_identity: Identity
    after_view_identity: Identity
    remaining_delta_records: Literal[0]
    view_preserved: Literal[True]
    visible_result_identity: Identity
    partitioned_base_preserved: Literal[True]
    routing_outcome_after: Literal["selected-certified"]
    total_partitions_after: int

class Counter(TypedDict):
    status: Literal["measured", "unsupported"]
    value: int | None
    unit: str
    provider: str
    reason: str | None

class CursorV1(TypedDict):
    """Logical continuation cursor."""
    key_hex: str
    sort_values: list[JsonValue]

class DefineLexicalIndexRequestV1(TypedDict):
    """Atomic durable lexical-index definition request."""
    lexical_index: LexicalIndexV1
    transaction_id: NotRequired[str | None]

class DefineVectorSpaceRequestV1(TypedDict):
    """Atomic durable vector-space definition request."""
    transaction_id: NotRequired[str | None]
    vector_space: VectorSpaceV1

class DeleteRequestV1(TypedDict):
    """Atomic durable delete batch."""
    keys_hex: list[str]
    transaction_id: NotRequired[str | None]

class DeleteVectorsRequestV1(TypedDict):
    """Atomic durable vector deletion batch."""
    keys_hex: list[str]
    transaction_id: NotRequired[str | None]
    vector_space: str

class Delta(TypedDict):
    before_base_identity: Identity
    before_view_identity: Identity
    after_base_identity: Identity
    after_view_identity: Identity
    upserted_vectors: Positive
    deleted_vectors: Positive
    upserts_visible: Literal[True]
    deletes_hidden: Literal[True]
    visible_result_identity: Identity

class ErrorV1(TypedDict):
    """Stable version 1 public error envelope."""
    code: str
    message: str
    request_id: str

class Eta(TypedDict):
    status: Literal["pending", "estimated", "completed"]
    estimated_remaining_nanos: None | int

class ExactAbstentionV1(TypedDict):
    """Stable exact-retrieval abstention evidence."""
    best_score_nanos: NotRequired[int | None]
    reason: ExactAbstentionReasonV1
    runner_up_score_nanos: NotRequired[int | None]
    scanned_candidates: int

class ExactRetrievalMatchV1(TypedDict):
    """One canonical exact-retrieval match."""
    key_hex: str
    score_nanos: int

class ExactRetrievalOutcomeV1Matches(TypedDict):
    """Accepted globally ranked matches."""
    matches: list[ExactRetrievalMatchV1]
    scanned_candidates: int
    status: Literal["matches"]

class ExactRetrievalOutcomeV1Abstained(TypedDict):
    """Typed normal abstention."""
    abstention: ExactAbstentionV1
    status: Literal["abstained"]

class ExactRetrievalRequestV1(TypedDict):
    """Durable exact-retrieval request under reference semantics v2."""
    limit: int
    minimum_margin_nanos: int
    minimum_score_nanos: int
    query: list[int]
    timeout_ms: NotRequired[int | None]
    vector_space: str

class ExactRetrievalResponseV1(TypedDict):
    """Proof-bearing durable exact-retrieval response."""
    outcome: ExactRetrievalOutcomeV1
    proof: RetrievalProofV1

class FilterV1MatchAll(TypedDict):
    """Match every record."""
    op: Literal["match_all"]

class FilterV1Exists(TypedDict):
    """Test whether a path resolves."""
    op: Literal["exists"]
    path: list[str]

class FilterV1Compare(TypedDict):
    """Compare one resolved value."""
    op: Literal["compare"]
    operator: CompareOperatorV1
    path: list[str]
    value: JsonValue

class FilterV1Prefix(TypedDict):
    """Test a string or bytes prefix."""
    op: Literal["prefix"]
    path: list[str]
    prefix: JsonValue

class FilterV1Contains(TypedDict):
    """Test array membership, string substring, or byte subsequence."""
    needle: JsonValue
    op: Literal["contains"]
    path: list[str]

class FilterV1All(TypedDict):
    """Require every child."""
    filters: list[FilterV1]
    op: Literal["all"]

class FilterV1Any(TypedDict):
    """Require at least one child."""
    filters: list[FilterV1]
    op: Literal["any"]

class FilterV1Not(TypedDict):
    """Negate one child."""
    filter: FilterV1
    op: Literal["not"]

class FinalReopen(TypedDict):
    base_identity: Identity
    view_identity: Identity
    delta_records: Literal[0]
    view_preserved: Literal[True]
    visible_result_identity: Identity
    routing_outcome: Literal["selected-certified"]
    total_partitions: int

class GetRequestV1(TypedDict):
    """Exact durable KV lookup."""
    key_hex: str

class GetResponseV1(TypedDict):
    """Proof-bearing exact lookup response."""
    found: bool
    proof: ProofV1
    record: NotRequired[RecordV1 | None]

class GroupKeyValueV1Missing(TypedDict):
    """The requested field path did not resolve."""
    kind: Literal["missing"]

class GroupKeyValueV1Value(TypedDict):
    """The path resolved, including when the structured value is explicit null."""
    kind: Literal["value"]
    value: JsonValue

class GroupResultV1(TypedDict):
    """One deterministic aggregate group."""
    key: list[GroupKeyValueV1]
    metrics: list[NamedMetricResultV1]

class HealthV1(TypedDict):
    """Liveness or readiness response."""
    status: str

class HybridAbstentionV1(TypedDict):
    """Both hybrid branches abstained normally."""
    lexical: HybridBranchAbsenceV1
    vector: HybridBranchAbsenceV1

class HybridExplanationV1(TypedDict):
    """Full deterministic explanation for one hybrid result."""
    final_rank: int
    fusion_score: int
    lexical_contribution: int
    lexical_rank: NotRequired[int | None]
    lexical_score_nanos: NotRequired[int | None]
    vector_contribution: int
    vector_rank: NotRequired[int | None]
    vector_score_nanos: NotRequired[int | None]

class HybridRetrievalMatchV1(TypedDict):
    """One canonical hybrid retrieval match."""
    explanation: HybridExplanationV1
    key_hex: str

class HybridRetrievalOutcomeV1Matches(TypedDict):
    """Fused or explicit single-modality matches."""
    lexical_absence: NotRequired[HybridBranchAbsenceV1 | None]
    matches: list[HybridRetrievalMatchV1]
    status: Literal["matches"]
    vector_absence: NotRequired[HybridBranchAbsenceV1 | None]

class HybridRetrievalOutcomeV1Abstained(TypedDict):
    """Both branches abstained."""
    abstention: HybridAbstentionV1
    status: Literal["abstained"]

class HybridRetrievalRequestV1(TypedDict):
    """Complete hybrid retrieval request under deterministic RRF semantics v1."""
    lexical: LexicalRetrievalRequestV1
    lexical_weight: int
    limit: int
    vector: ExactRetrievalRequestV1
    vector_weight: int

class HybridRetrievalResponseV1(TypedDict):
    """Proof-bearing deterministic hybrid retrieval response."""
    outcome: HybridRetrievalOutcomeV1
    proof: RetrievalProofV1

class HyphaeNativeANNDurableLocalQualificationV1(TypedDict):
    schema: Literal["hyphae-native-ann-durable-qualification-v1"]
    status: Literal["diagnostic"]
    source: dict[str, JsonValue]
    dataset: dict[str, JsonValue]
    build: Build
    quality: None | Quality
    lifecycle: dict[str, JsonValue]
    missing_gate_evidence: list[Literal["adaptive-routing-certification", "consolidation-visibility", "delta-visibility", "durable-reopen", "full-fanout-equality", "post-consolidation-reopen", "selected-recall-floor"]]
    claims: Literal[[]]
    closure_declared: Literal[False]

class HyphaeNativeHardwareCalibrationV1(TypedDict):
    schema: Literal["hyphae-native-hardware-calibration-v1"]
    mode: Literal["quick", "thorough"]
    status: Literal["stable", "unstable", "rejected"]
    accepted_for_scheduling: bool
    cache_status: Literal["disabled", "hit", "miss"]
    elapsed_ms: int
    identity: dict[str, JsonValue]
    policy: dict[str, JsonValue]
    feature_detection: dict[str, JsonValue]
    measurements: list[Measurement]
    selected_kernels: list[dict[str, JsonValue]]
    thread_scaling: dict[str, JsonValue]
    io_scaling: dict[str, JsonValue]
    coverage: dict[str, JsonValue]
    claims: list[JsonValue]

class HyphaeNativeHardwareProfileV1(TypedDict):
    schema: Literal["hyphae-native-hardware-profile-v1"]
    fingerprint: Digest
    cpu: dict[str, JsonValue]
    memory: dict[str, JsonValue]
    storage: dict[str, JsonValue]
    operating_system: dict[str, JsonValue]

class HyphaeNativePerformanceProgressV1(TypedDict):
    schema: Literal["hyphae-native-performance-progress-v1"]
    source_commit: Sha1
    source_tree: Sha1
    dataset_digest: Sha256
    operation: str
    stage: str
    sequence: int
    completed_units: int
    total_units: int
    unit: str
    elapsed_nanos: int
    status: Literal["running", "completed"]
    checkpoint_digest: None | Sha256
    details: dict[str, JsonValue]

class HyphaeNativePerformanceReceiptV1(TypedDict):
    schema: Literal["hyphae-native-performance-receipt-v1"]
    status: Literal["passed"]
    evidence_class: Literal["diagnostic-baseline", "regression-candidate", "qualification-candidate"]
    source: dict[str, JsonValue]
    environment: dict[str, JsonValue]
    workload: dict[str, JsonValue]
    dataset: dict[str, JsonValue]
    measurement: dict[str, JsonValue]
    counters: dict[str, JsonValue]
    correctness: dict[str, JsonValue]
    claims: list[JsonValue]
    closure_declared: Literal[False]

class HyphaeNativePerformanceSuiteV1(TypedDict):
    schema: Literal["hyphae-native-performance-suite-v1"]
    status: Literal["passed"]
    suite_profile_sha256: Sha256
    source_commit: Sha1
    source_tree: Sha1
    binary_sha256: Sha256
    clean: bool
    hardware_fingerprint: Sha256
    receipts: list[HyphaeNativePerformanceReceiptV1]
    claims: Literal[[]]
    closure_declared: Literal[False]

class HyphaeNativePersistentExecutionTopologyV1(TypedDict):
    schema: Literal["hyphae-native-execution-topology-v1"]
    hardware_fingerprint: str
    schedulable_compute_threads: int
    hard_affinity: bool
    numa_steal_policy: NumaStealPolicy
    pools: list[Pool]

class HyphaeNativeResourceGovernorPolicyV1(TypedDict):
    schema: Literal["hyphae-native-governor-policy-v1"]
    mode: Literal["latency", "bulk", "mixed"]
    hardware_fingerprint: Digest
    calibration_cache_key: Digest
    calibrated_worker_limit: int
    reserved_system_threads: int
    schedulable_compute_threads: int
    io_slots: int
    memory_bytes: int
    memory_headroom_percent: Literal[15]
    admission_queue_capacity: int
    foreground_burst_limit: Literal[16]
    class_limits: list[ClassLimit]

class HyphaeNativeSchedulerAuthorityV1(TypedDict):
    schema: Literal["hyphae-native-scheduler-authority-v1"]
    source_commit: str
    source_tree: str
    executable_blake3: Blake3
    mode: Literal["latency", "bulk", "mixed"]
    hardware_fingerprint: Blake3
    calibration_cache_key: Blake3
    input_canonical_sha256: dict[str, JsonValue]
    calibrated_worker_limit: int
    schedulable_compute_threads: int
    io_slots: int
    memory_bytes: int
    numa_pools: list[int | None]
    hard_affinity: bool
    numa_steal_policy_schema: Literal["hyphae-native-numa-steal-policy-v1"]
    numa_steal_status: Literal["not-applicable", "disabled", "calibrated"]
    numa_steal_thresholds: list[dict[str, JsonValue]]
    status: Literal["verified"]
    claims: list[JsonValue]

class HyphaeNativeThreadScalingCalibrationDiagnosticV1(TypedDict):
    """Diagnostic-only evidence. Source commit/tree come from an external exact-source authority; producer_executable_blake3 binds the independently hashed producer bytes. This schema never grants scheduling, governor, cache, G7, or closure authority."""
    schema: Literal["hyphae-native-hardware-calibration-diagnostic-v1"]
    authority: Literal[False]
    evidence_class: Literal["diagnostic-only"]
    claims: list[JsonValue]
    closure_declared: Literal[False]
    source: dict[str, JsonValue]
    platform: str
    identity: dict[str, JsonValue]
    policy: dict[str, JsonValue]
    surface: dict[str, JsonValue]

class HyphaeNativeVectorBulkBuildBakeoffV1(TypedDict):
    schema: Literal["hyphae-native-vector-bulk-bakeoff-v1"]
    status: Literal["diagnostic"]
    source_commit: str
    hardware_fingerprint: Digest
    governor_calibration_cache_key: Digest
    dataset: dict[str, JsonValue]
    build: dict[str, JsonValue]
    quality: dict[str, JsonValue]
    missing_gate_evidence: list[str]
    claims: Literal[[]]
    closure_declared: Literal[False]

class InitialReopen(TypedDict):
    base_identity: Identity
    view_identity: Identity
    selected_result_identity: Identity

class LexicalAbstentionV1(TypedDict):
    """Stable lexical abstention evidence."""
    query_tokens: list[str]
    reason: LexicalAbstentionReasonV1
    scanned_documents: int

class LexicalFieldContributionV1(TypedDict):
    """One configured-field contribution to a lexical term score."""
    field_length: int
    path: list[str]
    term_frequency: int

class LexicalFieldV1(TypedDict):
    """One configured field in an immutable lexical-index definition."""
    path: list[str]
    weight_micros: int

class LexicalIndexV1(TypedDict):
    """One immutable provider-free lexical-index definition."""
    fields: list[LexicalFieldV1]
    name: str

class LexicalRetrievalMatchV1(TypedDict):
    """One canonical lexical retrieval match."""
    key_hex: str
    score_nanos: int
    terms: list[LexicalTermContributionV1]

class LexicalRetrievalOutcomeV1Matches(TypedDict):
    """Accepted globally ranked matches."""
    matched_documents: int
    matches: list[LexicalRetrievalMatchV1]
    query_tokens: list[str]
    scanned_documents: int
    status: Literal["matches"]

class LexicalRetrievalOutcomeV1Abstained(TypedDict):
    """Typed normal abstention."""
    abstention: LexicalAbstentionV1
    status: Literal["abstained"]

class LexicalRetrievalRequestV1(TypedDict):
    """Durable provider-free lexical retrieval request under semantics v1."""
    lexical_index: str
    limit: int
    query: str
    timeout_ms: NotRequired[int | None]

class LexicalRetrievalResponseV1(TypedDict):
    """Proof-bearing durable lexical retrieval response."""
    outcome: LexicalRetrievalOutcomeV1
    proof: RetrievalProofV1

class LexicalTermContributionV1(TypedDict):
    """One canonical query-term contribution to a lexical result."""
    document_frequency: int
    fields: list[LexicalFieldContributionV1]
    score_nanos: int
    token: str

class Measurement(TypedDict):
    primitive: str
    variant: str
    input_size: int
    input_unit: str
    bytes_per_operation: int
    operations_per_sample: int
    maximum_operations_per_sample: int
    sample_count: int
    statistics: dict[str, JsonValue]
    correctness: dict[str, JsonValue]
    status: Literal["stable", "unstable", "rejected"]

class MetricValueV1Count(TypedDict):
    """Unsigned count."""
    kind: Literal["count"]
    value: int

class MetricValueV1Integer(TypedDict):
    """Checked signed integer, represented as decimal to preserve `i128`."""
    kind: Literal["integer"]
    value: NotRequired[str | None]

class MetricValueV1Value(TypedDict):
    """Minimum or maximum structured value."""
    kind: Literal["value"]
    value: NotRequired[JsonValue]

class NamedMetricResultV1(TypedDict):
    """Named aggregate result."""
    name: str
    result: MetricValueV1

class NamedMetricV1Count(TypedDict):
    """Count every matched record."""
    metric: Literal["count"]
    name: str

class NamedMetricV1Sum(TypedDict):
    """Checked integer sum."""
    metric: Literal["sum"]
    name: str
    path: list[str]

class NamedMetricV1Min(TypedDict):
    """Minimum non-null value."""
    metric: Literal["min"]
    name: str
    path: list[str]

class NamedMetricV1Max(TypedDict):
    """Maximum non-null value."""
    metric: Literal["max"]
    name: str
    path: list[str]

class NumaStealPolicy(TypedDict):
    schema: Literal["hyphae-native-numa-steal-policy-v1"]
    calibration_cache_key: str
    status: Literal["not-applicable", "disabled", "calibrated"]
    working_set_bytes: Literal[8388608]
    foreground_burst_limit: Literal[16]
    pools: list[NumaStealPool]

class NumaStealPool(TypedDict):
    worker_numa_node_id: NullableId
    steal_targets: list[NumaStealTarget]

class NumaStealTarget(TypedDict):
    home_numa_node_id: int
    remote_to_local_latency_ppm: int
    steal_after_nanoseconds: int

class Pool(TypedDict):
    numa_node_id: NullableId
    workers: list[Worker]

class ProofV1(TypedDict):
    """Portable result proof plus its downloadable witness reference."""
    anchor_digest: str
    checkpoint_digest: NotRequired[str | None]
    checkpoint_sequence: int
    data: str
    encoding: str
    proof_digest: str
    snapshot_digest: str
    witness: WitnessV1

class PutRequestV1(TypedDict):
    """Atomic durable put batch."""
    records: list[RecordV1]
    transaction_id: NotRequired[str | None]

class PutVectorsRequestV1(TypedDict):
    """Atomic durable vector upsert batch."""
    transaction_id: NotRequired[str | None]
    vector_space: str
    vectors: list[VectorV1]

class Quality(TypedDict):
    query_set_identity: Identity
    queries: Positive
    k: Positive
    ef_search: Positive
    selected_partitions: Literal[32]
    certified_selected_queries: Positive
    full_fanout_fallback_queries: Literal[0]
    maximum_searched_partitions: Literal[32]
    selected_query_recall_ppm: int
    minimum_selected_query_recall_ppm: int
    oracle_result_identity: Identity
    default_result_identity: Identity
    full_fanout_result_identity: Identity
    selected_result_identity: Identity
    full_fanout_equals_default: Literal[True]

class QueryRequestV1(TypedDict):
    """Complete version 1 structured query request."""
    aggregation: NotRequired[AggregationPlanV1 | None]
    cursor: NotRequired[CursorV1 | None]
    filter: NotRequired[FilterV1]
    limit: int
    sort: NotRequired[list[SortFieldV1]]
    timeout_ms: NotRequired[int | None]

class QueryResponseV1(TypedDict):
    """Proof-bearing structured query response."""
    aggregation: NotRequired[AggregationResultV1 | None]
    matched_records: int
    next_cursor: NotRequired[CursorV1 | None]
    proof: ProofV1
    rows: list[RecordV1]
    scanned_records: int

class RecordV1(TypedDict):
    """One structured record on the wire."""
    key_hex: str
    value: JsonValue

class RetrievalProofV1(TypedDict):
    """Portable retrieval proof plus its downloadable witness reference."""
    anchor_digest: str
    checkpoint_digest: NotRequired[str | None]
    checkpoint_sequence: int
    data: str
    encoding: str
    proof_digest: str
    snapshot_digest: str
    witness: WitnessV1

class SortFieldV1(TypedDict):
    """One versioned sort field."""
    direction: SortDirectionV1
    nulls: NullPlacementV1
    path: list[str]

class Statistics(TypedDict):
    unit: Literal["picoseconds_per_operation"]
    minimum: int
    median: int
    maximum: int
    median_absolute_deviation: int
    relative_mad_ppm: int
    relative_range_ppm: int
    median_bytes_per_second: int

class VectorSpaceV1(TypedDict):
    """One immutable durable vector-space definition."""
    dimension: int
    metric: VectorMetricV1
    name: str

class VectorV1(TypedDict):
    """One canonical signed-Q15 vector on the wire."""
    key_hex: str
    values: list[int]

class WitnessV1(TypedDict):
    """Download reference for one canonical logical snapshot."""
    file_bytes: int
    path: str

class Worker(TypedDict):
    worker_index: int
    numa_node_id: NullableId
    logical_processor_id: NullableId
    socket_id: NullableId
    core_id: NullableId
    smt_rank: NullableId

class WorkerPoint(TypedDict):
    worker_count: int
    variant: str
    bytes_per_operation: int
    operations_per_sample: int
    maximum_operations_per_sample: Literal[1048576]
    batch_calibration_status: Literal["converged", "not-converged"]
    samples_picoseconds_per_operation: list[int]
    statistics: Statistics
    correctness: dict[str, JsonValue]
    status: Literal["stable", "unstable"]

Blake3: TypeAlias = str
Class: TypeAlias = Literal["foreground-point", "foreground-bounded", "mutation", "bulk", "maintenance", "recovery", "administrative"]
CompareOperatorV1: TypeAlias = Literal["equal"] | Literal["not_equal"] | Literal["less"] | Literal["less_or_equal"] | Literal["greater"] | Literal["greater_or_equal"]
Digest: TypeAlias = str
ExactAbstentionReasonV1: TypeAlias = Literal["no_candidates"] | Literal["below_threshold"] | Literal["ambiguous"]
ExactRetrievalOutcomeV1: TypeAlias = ExactRetrievalOutcomeV1Matches | ExactRetrievalOutcomeV1Abstained
FilterV1: TypeAlias = FilterV1MatchAll | FilterV1Exists | FilterV1Compare | FilterV1Prefix | FilterV1Contains | FilterV1All | FilterV1Any | FilterV1Not
GitObject: TypeAlias = str
GroupKeyValueV1: TypeAlias = GroupKeyValueV1Missing | GroupKeyValueV1Value
HybridBranchAbsenceV1: TypeAlias = Literal["lexical_no_candidates"] | Literal["vector_no_candidates"] | Literal["vector_below_threshold"] | Literal["vector_ambiguous"]
HybridRetrievalOutcomeV1: TypeAlias = HybridRetrievalOutcomeV1Matches | HybridRetrievalOutcomeV1Abstained
Identity: TypeAlias = str
LexicalAbstentionReasonV1: TypeAlias = Literal["no_candidates"]
LexicalRetrievalOutcomeV1: TypeAlias = LexicalRetrievalOutcomeV1Matches | LexicalRetrievalOutcomeV1Abstained
MetricValueV1: TypeAlias = MetricValueV1Count | MetricValueV1Integer | MetricValueV1Value
NamedMetricV1: TypeAlias = NamedMetricV1Count | NamedMetricV1Sum | NamedMetricV1Min | NamedMetricV1Max
Nonnegative: TypeAlias = int
NonnegativeInteger: TypeAlias = int
NullPlacementV1: TypeAlias = Literal["first"] | Literal["last"]
NullableId: TypeAlias = int | None
OptionalNonnegativeInteger: TypeAlias = None | int
OptionalPositiveInteger: TypeAlias = None | int
OptionalString: TypeAlias = None | str
Positive: TypeAlias = int
Recall: TypeAlias = int
Sha: TypeAlias = str
Sha1: TypeAlias = str
Sha256: TypeAlias = str
SortDirectionV1: TypeAlias = Literal["ascending"] | Literal["descending"]
UniqueStrings: TypeAlias = list[str]
VectorMetricV1: TypeAlias = Literal["cosine_q15_nanos"]

__all__ = [
    "AggregationPlanV1",
    "AggregationResultV1",
    "ApiLimitsV1",
    "Blake3",
    "Build",
    "CONTRACT_SHA256",
    "CapabilitiesV1",
    "Class",
    "ClassLimit",
    "CommitReceiptV1",
    "CompareOperatorV1",
    "Consolidation",
    "Counter",
    "CursorV1",
    "DefineLexicalIndexRequestV1",
    "DefineVectorSpaceRequestV1",
    "DeleteRequestV1",
    "DeleteVectorsRequestV1",
    "Delta",
    "Digest",
    "ErrorV1",
    "Eta",
    "ExactAbstentionReasonV1",
    "ExactAbstentionV1",
    "ExactRetrievalMatchV1",
    "ExactRetrievalOutcomeV1",
    "ExactRetrievalOutcomeV1Abstained",
    "ExactRetrievalOutcomeV1Matches",
    "ExactRetrievalRequestV1",
    "ExactRetrievalResponseV1",
    "FilterV1",
    "FilterV1All",
    "FilterV1Any",
    "FilterV1Compare",
    "FilterV1Contains",
    "FilterV1Exists",
    "FilterV1MatchAll",
    "FilterV1Not",
    "FilterV1Prefix",
    "FinalReopen",
    "GetRequestV1",
    "GetResponseV1",
    "GitObject",
    "GroupKeyValueV1",
    "GroupKeyValueV1Missing",
    "GroupKeyValueV1Value",
    "GroupResultV1",
    "HealthV1",
    "HybridAbstentionV1",
    "HybridBranchAbsenceV1",
    "HybridExplanationV1",
    "HybridRetrievalMatchV1",
    "HybridRetrievalOutcomeV1",
    "HybridRetrievalOutcomeV1Abstained",
    "HybridRetrievalOutcomeV1Matches",
    "HybridRetrievalRequestV1",
    "HybridRetrievalResponseV1",
    "HyphaeNativeANNDurableLocalQualificationV1",
    "HyphaeNativeHardwareCalibrationV1",
    "HyphaeNativeHardwareProfileV1",
    "HyphaeNativePerformanceProgressV1",
    "HyphaeNativePerformanceReceiptV1",
    "HyphaeNativePerformanceSuiteV1",
    "HyphaeNativePersistentExecutionTopologyV1",
    "HyphaeNativeResourceGovernorPolicyV1",
    "HyphaeNativeSchedulerAuthorityV1",
    "HyphaeNativeThreadScalingCalibrationDiagnosticV1",
    "HyphaeNativeVectorBulkBuildBakeoffV1",
    "Identity",
    "InitialReopen",
    "JsonValue",
    "LexicalAbstentionReasonV1",
    "LexicalAbstentionV1",
    "LexicalFieldContributionV1",
    "LexicalFieldV1",
    "LexicalIndexV1",
    "LexicalRetrievalMatchV1",
    "LexicalRetrievalOutcomeV1",
    "LexicalRetrievalOutcomeV1Abstained",
    "LexicalRetrievalOutcomeV1Matches",
    "LexicalRetrievalRequestV1",
    "LexicalRetrievalResponseV1",
    "LexicalTermContributionV1",
    "Measurement",
    "MetricValueV1",
    "MetricValueV1Count",
    "MetricValueV1Integer",
    "MetricValueV1Value",
    "NamedMetricResultV1",
    "NamedMetricV1",
    "NamedMetricV1Count",
    "NamedMetricV1Max",
    "NamedMetricV1Min",
    "NamedMetricV1Sum",
    "Nonnegative",
    "NonnegativeInteger",
    "NullPlacementV1",
    "NullableId",
    "NumaStealPolicy",
    "NumaStealPool",
    "NumaStealTarget",
    "OptionalNonnegativeInteger",
    "OptionalPositiveInteger",
    "OptionalString",
    "Pool",
    "Positive",
    "ProofV1",
    "PutRequestV1",
    "PutVectorsRequestV1",
    "Quality",
    "QueryRequestV1",
    "QueryResponseV1",
    "Recall",
    "RecordV1",
    "RetrievalProofV1",
    "Sha",
    "Sha1",
    "Sha256",
    "SortDirectionV1",
    "SortFieldV1",
    "Statistics",
    "UniqueStrings",
    "VectorMetricV1",
    "VectorSpaceV1",
    "VectorV1",
    "WitnessV1",
    "Worker",
    "WorkerPoint",
]
